import Head from 'next/head';
import Image from 'next/image';
import Layout from '../components/layout';
import { Inter } from '@next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Mentaya</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className=" mx-auto flex h-screen max-w-6xl">
        <div className=" w-1/2 py-32">
          <h1 className={`${inter.className} mb-5 text-6xl font-extrabold text-gray-700`}>
            A simple chat bot for your Apps
          </h1>
          <p className={`${inter.className} mb-10 text-xl leading-relaxed text-gray-700`}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae ab vitae quos,
            cupiditate voluptatum accusamus sequi cum architecto laborum minima iusto impedit.
          </p>
          <Link
            href="#"
            className={`${inter.className} rounded-md border border-pink-600 bg-pink-600 py-3 px-4 text-white transition ease-in-out hover:bg-pink-700`}
          >
            Get Started
          </Link>
        </div>
        <div>image</div>
      </section>
    </Layout>
  );
}
